name: Maven CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar Java y Maven
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      # 3. Ejecutar los plugins
      - name: Build and Test
        run: mvn clean verify

      # 4. Ejecutar Checkstyle
      - name: Checkstyle Analysis
        run: mvn checkstyle:checkstyle
        continue-on-error: true

      # 5. Ejecutar SpotBugs
      - name: SpotBugs Analysis
        run: mvn spotbugs:check
        continue-on-error: true

      # 6. Generar reporte de cobertura con JaCoCo
      - name: Generate Coverage Report
        run: mvn jacoco:report
